Implementation of Tax statement - incl. translations
imat-open-source/German-Accounting pull request #9
Opened 2023-09-07 08:44 UTC by larsmaeurer

issue #8 

- Refactored and moved client side in public/js and extented via hooks.py for ease of maintenance
- Implemented server side validation for Quotation, Sales Order, Sales Invoice
- removed client script json as moved in code
- translation of all names and texts

2023-09-07 14:29 UTC, Mutantpenguin commented on german_accounting/german_accounting/custom/quotation.json
What about using `create_custom_fields` with only the attributes which differ from the default?

The usage of this can be seen in `erpnext/regional/united_states/setup.py` for example.

This would need to be run during migration with `after_migrate` in `hooks.py`.

2023-09-07 14:30 UTC, Markus-Lobedann commented on german_accounting/german_accounting/custom/quotation.json
What about using create_custom_fields with only the attributes which differ from the default?

The usage of this can be seen in erpnext/regional/united_states/setup.py for example.

This would need to be run during migration with after_migrate in hooks.py.

(should be done for all the fields)

2023-09-07 14:38 UTC, liesenja requested changes

2023-09-07 14:38 UTC, liesenja commented on german_accounting/german_accounting/custom/quotation.json
>     "fieldtype": "Data",
why is this of the type data?  
Logically a select field would be better. 

Additionally, why is this field even visible for the user? It will only cause confusion for the user

2023-09-07 14:38 UTC, liesenja commented on german_accounting/events/extended_tax_category.py
> +        elif item.item_group == "Services":
the item group is a tree. That means that "Goods" can also have Item Groups beneath them. Those groups are currently not involved in you check.

Luckly you can use a function for the trees that gives you all the descendants of the group. The function is called `get_descendants_of`. Here you can find [more information](https://github.com/frappe/frappe/blob/1a563164d7ed85f46c26a685eabd326b101456e6/frappe/utils/nestedset.py#L395) about this.

2023-09-08 14:02 UTC, Markus-Lobedann commented on german_accounting/hooks.py
> +	}
Should be called on `before_validate`, as `validate` is only for checking values in the doc, and not for changing it.

2023-09-13 09:47 UTC, larsmaeurer commented on german_accounting/events/extended_tax_category.py
> +        doc.vat_print_display = "19% VAT"
I would actually leave this as it is, the case distinction is then easier to keep track of when you look back in later or want to change something....

2023-09-13 10:23 UTC, beingeek commented on german_accounting/public/js/extended_tax_category.js
It addon to user experience; whenever user change something in UI user will experience WYSIWYG as python code will only execute when document is saved but js will show result on user action on fields, so there's no harm it won't make system much slower.

2023-09-13 10:38 UTC, beingeek commented on german_accounting/hooks.py
> +	}
Hi @Markus-Lobedann  there's no need of before_validate as validate event can also change values; its like it will do as how we program it. Theoretically there's no restriction on validate event that it should only check values.
you can see this validate event in sales invoice: https://github.com/frappe/erpnext/blob/develop/erpnext/accounts/doctype/sales_invoice/sales_invoice.py#L84

2023-09-13 10:46 UTC, beingeek commented on german_accounting/german_accounting/custom/quotation.json
We can use create_custom_fields and create fields programmatically which is same as creating field via customize form and exporting, and it can be done its really required but  in essence its same.

2023-09-14 06:12 UTC, beingeek commented on german_accounting/hooks.py
> +    "Sales Order" : "public/js/sales_invoice.js",
Hi @liesenja  this extension was working fine as all 3 files are importing same file (extended_tax_category.js) at the moment  and i kept 3 separate files so that in future possibly there will be code custom script which will not be some in all files. So common file is abstract and imported. But anyways i'm disabling this code from hooks, because this functionality is already implemented in python code.

2023-09-14 06:26 UTC, liesenja commented on german_accounting/hooks.py
> +    "Sales Order" : "public/js/sales_invoice.js",
Thats is not exactly what I meant. 
You created a `sales_invoice.js`, a `sales_order.js` and a `quotation.js`. I also know that all of them do the same thing by importing the `extended_tax_category.js`. 

However it would be great if you could use the correct file for each doctype since now you include the `sales_invoice.js` into the `Sales Order` Doctype, which technically makes no difference right now, but logically it is confusing.

2023-09-14 06:54 UTC, beingeek commented on german_accounting/hooks.py
> +    "Sales Order" : "public/js/sales_invoice.js",
Yes i fixed, Thanks for pointing

2023-09-14 08:54 UTC, beingeek commented on german_accounting/events/extended_tax_category.py
> +        elif item.item_group == "Services":
@larsmaeurer please check this, how we gonna implement out of 2 ways we discussed earlier. So that we can take this farther

2023-09-14 08:54 UTC, beingeek commented on german_accounting/public/js/extended_tax_category.js
done

2023-09-14 08:54 UTC, beingeek commented on german_accounting/german_accounting/custom/quotation.json
>     "fieldtype": "Data",
Done

2023-09-14 08:54 UTC, beingeek commented on german_accounting/events/extended_tax_category.py
> +            services += item.qty * item.price_list_rate
Done

2023-09-14 08:55 UTC, beingeek commented on german_accounting/public/js/extended_tax_category.js
> +	        if (cur_frm.doc.items[row].item_group == "Goods") {goods += cur_frm.doc.items[row].qty * cur_frm.doc.items[row].price_list_rate}
Done

2023-09-14 08:55 UTC, beingeek commented on german_accounting/public/js/extended_tax_category.js
> +	    var services = 0;
Done

2023-09-14 08:55 UTC, beingeek commented on german_accounting/german_accounting/custom/quotation.json
> +   "options": "Yes\nNo",
Done

2023-09-14 08:55 UTC, beingeek commented on german_accounting/german_accounting/custom/quotation.json
Done

2023-09-14 09:39 UTC, larsmaeurer commented on german_accounting/events/extended_tax_category.py
> +        elif item.item_group == "Services":
If this function "get_descendants_of" finds the descendants of an entry, it should be enough to write all these descendants of "Goods" and "Services" (if they exist sometime) into 2 lists and then test if the item's item group appears in one of these lists?
This way we could also ensure for the future that the script works even if another item group than "Goods" or "Services" is used.

2023-09-14 10:12 UTC, liesenja commented on german_accounting/german_accounting/custom/quotation.json
>     "fieldtype": "Data",
tthe field is still a data field, is there a reason for that?  
As I already stated I think a select field would be better since it has the benefit of checking that no one tempered with the value.

2023-09-14 10:18 UTC, beingeek commented on german_accounting/german_accounting/custom/quotation.json
>     "fieldtype": "Data",
Its a hidden field and no chances of tempering

2023-09-14 10:19 UTC, liesenja commented on german_accounting/public/js/extended_tax_category.js
now the js files are saved without purpose. It would be best to remove them to keep the project as slim as possible.  
If we at some point need this file again we still have it in the commit history

2023-09-14 10:25 UTC, beingeek commented on german_accounting/events/extended_tax_category.py
> +        elif item.item_group == "Services":
OK

2023-09-14 11:01 UTC, larsmaeurer commented on german_accounting/events/extended_tax_category.py
> +        elif item.item_group == "Services":
...in progress... :-)

2023-09-14 11:32 UTC, Markus-Lobedann commented on german_accounting/german_accounting/custom/quotation.json
Thanks, I really like how you solved this.

I just think you shouldn't delete them by hand via SQL and go through the controller.

More along the lines of this example (extracted from line 61 in `frappe/core/doctype/domain/domain.py`):
```python
custom_field_name = frappe.db.get_value(
						"Custom Field", dict(dt=doctype, fieldname=custom_field_detail.get("fieldname"))
					)
					if custom_field_name:
						frappe.delete_doc("Custom Field", custom_field_name)
```

2023-09-14 11:39 UTC, Markus-Lobedann commented on german_accounting/hooks.py
> +	}
Technically you are right, semantically you are not. Frappes own documentations says that you should only validate and throw errors in this event.

But apart from that we discussed this whole topic internally today and came to the conclusion, that this whole logic may only run during `on_submit`, and that for 2 different reasons:
* I'ts just not necessary before submitting
* afterwards nothing can and may change which would affect this logic

@larsmaeurer Did we overlook something or are you ok with this?

2023-09-14 11:41 UTC, Markus-Lobedann commented on german_accounting/german_accounting/custom/quotation.json
>     "fieldtype": "Data",
Does this even need to be a custom field? We can only see it beeing used as a temporary variable inside the current logic.

Apart from that it really should be a select field with only 2 allowed values.

2023-09-14 12:36 UTC, larsmaeurer commented on german_accounting/hooks.py
> +	}
@Markus-Lobedann
"on_submit": Called after submission.
...this is actually the same as "validate", except that the script is not triggered before saving, but after saving/when submitted.
This should be ok :-)

2023-09-14 13:07 UTC, larsmaeurer commented on german_accounting/german_accounting/custom/quotation.json
>     "fieldtype": "Data",
That's correct, the field doesn't need to exist at all. It would be enough to use a variable instead of the field and adjust the case distinction accordingly.
I originally introduced this more for testing purposes.
--> However, such a field (even when hidden) would have the advantage that one can also access the result of the calculation outside of the running script. e.g. one could make something dependent on it in the print format, which otherwise becomes rather difficult, because this info is then lost...

2023-09-15 02:43 UTC, beingeek commented on german_accounting/hooks.py
> +	}
I think @Markus-Lobedann is right on this point on_submit only run once but validate execute whenever doc is saved. So we can safely execute on on_submit, additionally is there any validation require for this before submitting?

2023-09-15 02:46 UTC, beingeek commented on german_accounting/public/js/extended_tax_category.js
Kept only if there's chance of reusing, that's why i commented functionality in hooks.py. Removed now

2023-09-15 02:50 UTC, beingeek commented on german_accounting/german_accounting/custom/quotation.json
>     "fieldtype": "Data",
So what's the final decision of removing or keeping field? If we're keeping this than i will make this select field.

2023-09-15 02:50 UTC, beingeek commented on german_accounting/german_accounting/custom/quotation.json
Done

2023-09-15 07:13 UTC, Markus-Lobedann commented on german_accounting/german_accounting/custom/quotation.json
>     "fieldtype": "Data",
Lars must decide since I am only involved with the technical side and don't know what needs to be done further down the line with this field
I am a great supporter of YAGNI though. 😊

@larsmaeurer
Is there anything planned with this field yet?
If we do like you said I would expect the same reasoning for the other fields though:
* only store the **state** about the taxation/vat in a field
* in the print format, decide which string to display

2023-09-15 07:25 UTC, Markus-Lobedann commented on german_accounting/hooks.py
> +	}
I don't think so.

But I just realized that `on_submit` is slightly wrong since it runs after saving the doc, so we must use `before_submit` instead.

2023-09-15 08:27 UTC, beingeek commented on german_accounting/hooks.py
> +	}
Alright noted

2023-09-15 08:52 UTC, larsmaeurer commented on german_accounting/german_accounting/custom/quotation.json
>     "fieldtype": "Data",
The field is not required. We can remove it by using a variable instead of the field.
The information that would have been in this field can also be determined again at any time.
-->Field is unnecessary, use variable.

2023-09-15 09:27 UTC, beingeek commented on german_accounting/events/extended_tax_category.py
> +        elif item.item_group == "Services":
done

2023-09-15 09:29 UTC, beingeek commented on german_accounting/german_accounting/custom/quotation.json
>     "fieldtype": "Data",
Done

2023-09-18 10:37 UTC, beingeek commented on german_accounting/events/extended_tax_category.py
> +            item_groups + descendants_item_group
Oh yes :p
Thanks for mentioning

2023-09-18 11:13 UTC, beingeek commented on german_accounting/events/extended_tax_category.py
> +            item_groups + descendants_item_group
Fixed, please check

2023-10-23 14:19 UTC, Markus-Lobedann commented on german_accounting/events/extended_tax_category.py
> +        if item.item_group in get_parent_and_descendants_list("Goods"):
`get_parent_and_descendants_list` is loop invariant and must be called only once outside the loop

2023-10-25 04:47 UTC, beingeek commented on german_accounting/events/extended_tax_category.py
> +        if item.item_group in get_parent_and_descendants_list("Goods"):
Please elaborate more on this why its loop loop invariant as we are looping through Items table and checking checking whether item have specific Item Group if yes, then it add amount on item to a variable. So i think it should be loop, any alternative algo is appreciated if you can share

2023-10-26 14:51 UTC, Markus-Lobedann commented on german_accounting/events/extended_tax_category.py
> +        if item.item_group in get_parent_and_descendants_list("Goods"):
The loop is totally correct, I just mean calling `get_parent_and_descendants_list` is loop invariant. Regardless of how many times it gets called with the same argument in the loop, it will always return the same data.

This should be changed like this:
```python
item_group_list_goods: list[str] = get_parent_and_descendants_list("Goods")
item_group_list_services: list[str] = get_parent_and_descendants_list("Services")

for item in doc.get("items"):
    if item.item_group in item_group_list_goods:
        goods_amt_sum += flt(item.amount)
    elif item.item_group in item_group_list_services:
        services_amt_sum += flt(item.amount)
```

2023-10-28 12:50 UTC, beingeek commented on german_accounting/events/extended_tax_category.py
> +        if item.item_group in get_parent_and_descendants_list("Goods"):
Noted

2023-11-02 19:34 UTC, closed without merging